apiVersion: apps/v1
kind: Deployment
metadata:
  name: my-ai-app
spec:
  replicas: 1
  selector:
    matchLabels:
      app: my-ai-app
  template:
    metadata:
      labels:
        app: my-ai-app
    spec:
      nodeSelector:
        kubernetes.io/hostname: ubuntu  # Use the correct node name
      imagePullSecrets:
        - name: nexus-secret
      containers:
        - name: my-ai-app
          image: 192.168.8.113:30085/my-repository/my-new-ai-assistant:v1
          ports:
            - containerPort: 8501
---
apiVersion: v1
kind: Service
metadata:
  name: my-ai-app
spec:
  selector:
    app: my-ai-app
  ports:
    - protocol: TCP
      port: 80
      targetPort: 8501
  type: ClusterIP
