apiVersion: apps/v1
kind: Deployment
metadata:
  name: ai-assistant-deployment
  namespace: ai-ns
spec:
  replicas: 1
  selector:
    matchLabels:
      app: ai-assistant
  template:
    metadata:
      labels:
        app: ai-assistant
    spec:
      imagePullSecrets:
        - name: nexus-secret
      containers:
      - name: ai-assistant
        image: 127.0.0.1:30085/my-repository/my-new-ai-assistant:v3
        ports:
        - containerPort: 8501
---
apiVersion: v1
kind: Service
metadata:
  name: ai-assistant-service
  namespace: ai-ns
spec:
  selector:
    app: ai-assistant
  ports:
    - protocol: TCP
      port: 8501  # Service port
      targetPort: 8501  # Container port
  type: ClusterIP

