apiVersion: v1
kind: Service
metadata:
  name: nexus-service-for-docker-hosted-registry
  namespace: nexus-ns
spec:
  ports:
    - port: 8085
      targetPort: 8085
      protocol: TCP
  selector:
    app: nexus

