apiVersion: v1
kind: Service
metadata:
  name: nexus-service-for-docker-hosted-registry
  namespace: nexus-ns
spec:
  type: NodePort  # Change from ClusterIP to NodePort
  selector:
    app: nexus
  ports:
    - protocol: TCP
      port: 8085        # Inside Kubernetes
      targetPort: 8085  # Inside the Pod
      nodePort: 30085   # External port (use any between 30000-32767)
