[theme]
primaryColor = "#2AAA8A"
backgroundColor = "#0E1117"
secondaryBackgroundColor = "#262730"
textColor = "#FAFAFA"
font = "sans serif"

[server]
headless = true
port = 8501
enableCORS = false
address = "0.0.0.0"
fileWatcherType = "poll"
